version: '3.9'

services:
  EmailAPI:
    build: \Github_Repos\Project_1\Project_1_EmailAPI
    image: email_api:latest
    container_name: EmailAPI
    ports:
      - "8000:8000"
    depends_on:
      - db
  ReimbursementAPI:
    build: Project_1_ReimbursementAPI
    image: reimbursement_api:latest
    container_name: ReimbursementAPI
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password1!
      - MYSQL_ROOT_USER=root
  prom:
    image: 'bitnami/prometheus'
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"