server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    username: root
    password: password1!
    url: jdbc:mysql://db/Project_1
jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  show-sql: true